#!/usr/bin/env php
<?php
  file_put_contents('/etc/php/7.2/mods-available/pharbuilding.ini', implode("\n", [
    'phar.readonly=0',
    'display_errors=1',
    'display_startup_errors=1',
  ]));
  shell_exec('phpenmod pharbuilding');
