#!/bin/bash

# fix tmp permission
# chmod 777 /tmp

# configure the libraries
# ldconfig

# Enable or disable php extensions if you need: phpenmod, phpdismod
# phpenmod amqp
# phpenmod apcu
# phpenmod ast
# phpenmod bcmath
# phpenmod bz2
# phpenmod calendar
# phpenmod couchbase
# phpenmod ctype
# phpenmod curl
# phpenmod dba
# phpenmod dom
# phpenmod ds
# phpenmod enchant
# phpenmod ev
# phpenmod event
# phpenmod exif
# phpenmod fann
# phpenmod fileinfo
# phpenmod ftp
# phpenmod gd
# phpenmod geoip
# phpenmod geospatial
# phpenmod gettext
# phpenmod gmp
# phpenmod gnupg
# phpenmod grpc
# phpenmod hprose
# phpenmod hrtime
# phpenmod iconv
# phpenmod imagick
# phpenmod intl
# phpenmod jsond
# phpenmod libevent
# phpenmod mbstring
# phpenmod memcached
# phpenmod molten
# phpenmod mongodb
# phpenmod mysqli
# phpenmod mysqlnd
# phpenmod opcache
# phpenmod opencensus
# phpenmod pdo
# phpenmod pdo_mysql
# phpenmod pdo_pgsql
# phpenmod pdo_sqlite
# phpenmod pgsql
# phpenmod phar
# phpenmod phpng_xhprof
# phpenmod posix
# phpenmod psr
# phpenmod raphf
# phpenmod rar
# phpenmod readline
# phpenmod redis
# phpenmod request
# phpenmod rrd
# phpenmod seaslog
# phpenmod shmop
# phpenmod simplexml
# phpenmod soap
# phpenmod sockets
# phpenmod sodium
# phpenmod spx
# phpenmod sqlite3
# phpenmod ssh2
# phpenmod swoole
# phpenmod sync
# phpenmod sysvmsg
# phpenmod sysvsem
# phpenmod sysvshm
# phpenmod tidy
# phpenmod tokenizer
# phpenmod uv
# phpenmod v8
# phpenmod v8js
# phpenmod varnish
# phpenmod vcollect
# phpenmod vips
# phpenmod wddx
# phpenmod xdebug
# phpenmod xml
# phpenmod xmlreader
# phpenmod xmlrpc
# phpenmod xmlwriter
# phpenmod xsl
# phpenmod yac
# phpenmod yaf
# phpenmod yar
# phpenmod zip
# phpenmod zmq

# nginx cache
mkdir -p /app/var/cache/nginx/fastcgi
mkdir -p /app/var/cache/nginx/proxy
find /app/var/cache/nginx -type f -delete

# application cache
mkdir -p /app/var/cache/application/php
mkdir -p /app/var/cache/application/nodejs
find /app/var/cache/application -type f -delete

# permissions
chmod 777 /app/var/cache -R
chmod 777 /app/var/logs -R

# upload path
mkdir -p /app/var/tmp/uploads
find /app/var/tmp/uploads -type f -delete
chmod 777 /app/var/tmp -R

# Install global and local packages
# yarn global add grunt-cli
# cd /app/app && composer update
# cd /app/app && yarn install --pure-lockfile
# cd /app/app && grunt build

# optimize autoload on
if [ "$AASAAM_APP_ENV" = "prod" ]; then
  cd /app/app && composer dump-autoload --optimize --no-dev
fi

# Run supervisor
if [ -e "/app/etc/supervisor/supervisor.ini" ]; then
  supervisord -c /app/etc/supervisor/supervisor.ini
fi

# echo "fastcgi_param AASAAM_APP_ENV '$AASAAM_APP_ENV';" > /app/var/cache/nginx/fastcgi_param
# echo "fastcgi_param AASAAM_APP_PORT '$AASAAM_APP_PORT';" >> /app/var/cache/nginx/fastcgi_param
# echo "proxy_set_header X-Aasaam-App-Env '$AASAAM_APP_ENV';" > /app/var/cache/nginx/proxy_headers
# echo "proxy_set_header X-Aasaam-App-Port '$AASAAM_APP_PORT';" > /app/var/cache/nginx/proxy_headers

# start php and nginx
service php7.1-fpm start
service nginx start
