#!/bin/bash

# for adding configurations
sleep 3

# echo set environment for all
echo "HOSTNAME=$HOSTNAME" >> /etc/environment
echo "AASAAM_APPNAME=$AASAAM_APPNAME" >> /etc/environment
echo "AASAAM_DC=$AASAAM_DC" >> /etc/environment
echo "AASAAM_COUNTRY=$AASAAM_COUNTRY" >> /etc/environment

# clear temporaries
rm -rf /tmp/*
rm -rf /tmpfs/*

# make directories
mkdir -p /tmp/php/spx
mkdir -p /tmpfs/fluentbit
mkdir -p /tmpfs/run
mkdir -p /tmpfs/logs
mkdir -p /tmpfs/nginx/fastcgi/cache
mkdir -p /tmpfs/nginx/proxy/cache
mkdir -p /tmpfs/php/seaslog
mkdir -p /tmpfs/php/session
mkdir -p /tmpfs/php/soap
mkdir -p /tmpfs/php/tmp
mkdir -p /tmpfs/php/upload
mkdir -p /tmpfs/php/xdebug

# set permission 
chmod 777 /tmp -R
chmod 777 /tmpfs -R

# init dhparm
if [ -e "/app/etc/nginx/conf.d/addon/dhparam.pem" ]; then
  openssl dhparam -out /app/etc/nginx/conf.d/addon/dhparam.pem 2048
fi