#!/bin/bash

# php extensions
# phpenmod amqp
# phpenmod apcu
# phpenmod ast
# phpenmod couchbase
# phpenmod ds
# phpenmod ev
# phpenmod fann
# phpenmod geohash
# phpenmod geoip
# phpenmod geospatial
# phpenmod gnupg
# phpenmod grpc
# phpenmod hprose
# phpenmod hrtime
# phpenmod imagick
# phpenmod libevent
# phpenmod libsodium
# phpenmod memcached
# phpenmod molten
# phpenmod mongodb
# phpenmod opencensus
# phpenmod phpng_xhprof
# phpenmod raphf
# phpenmod rar
# phpenmod redis
# phpenmod request
# phpenmod rrd
# phpenmod seaslog
# phpenmod sodium
# phpenmod spx
# phpenmod ssh2
# phpenmod swoole
# phpenmod sync
# phpenmod uv
# phpenmod v8
# phpenmod v8js
# phpenmod varnish
# phpenmod vcollect
# phpenmod vips
# phpenmod xdebug
# phpenmod yac
# phpenmod yaf
# phpenmod yaml
# phpenmod yar
# phpenmod zmq

mkdir -p /app/var/logs && chown www-data:www-data /app/var/logs -R
mkdir -p /app/var/tmp && chown www-data:www-data /app/var/tmp -R
mkdir -p /app/var/cache/nginx/fastcgi \
  && mkdir -p /app/var/cache/nginx/proxy \
  && chown www-data:www-data /app/var/cache/nginx -R

# cd /app/app && yarn install
# cd /app/app && composer update
# cd /app/app && grunt build

if [ -e "/app/etc/supervisor/supervisor.ini" ]; then
  supervisord -c /app/etc/supervisor/supervisor.ini
fi

service cron start
service php7.1-fpm start
service nginx start
