[www]
user = www-data
group = www-data
listen = 127.0.0.1:9000
listen.owner = www-data
listen.group = www-data
listen.mode = 0660
pm.status_path = /__status/fpm
pm = dynamic
pm.max_children = 128
pm.start_servers = 64
pm.min_spare_servers = 64
pm.max_spare_servers = 128
pm.max_requests = 1024
catch_workers_output = yes
security.limit_extensions = .php
<?php if ($phpfpmslowlog): ?>
slowlog = /tmpfs/logs/php.fpm.slow.log
request_slowlog_timeout = 2s
<?php endif; ?>
<?php if ($phpfpmaccesslog): ?>
access.log = /tmpfs/logs/php.fpm.access.log
access.format = "%m '%r%Q%q' '%{%a, %d %b %Y %T %z}T' %{mili}d %{kilo}M %C"
<?php endif; ?>
php_admin_value[include_path] = "."
